// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase配置 - 从GoogleService-Info.plist获取的真实配置
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCibaFjlPVFArgWh-dYeW33NZ7zOUHH1rk',
    appId: '1:742358725365:web:7a45ba60ed1de60faf8bbc',
    messagingSenderId: '742358725365',
    projectId: 'ftrainerlogbook',
    authDomain: 'ftrainerlogbook.firebaseapp.com',
    storageBucket: 'ftrainerlogbook.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCibaFjlPVFArgWh-dYeW33NZ7zOUHH1rk',
    appId: '1:742358725365:android:7a45ba60ed1de60faf8bbc',
    messagingSenderId: '742358725365',
    projectId: 'ftrainerlogbook',
    storageBucket: 'ftrainerlogbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCibaFjlPVFArgWh-dYeW33NZ7zOUHH1rk',
    appId: '1:742358725365:ios:7a45ba60ed1de60faf8bbc',
    messagingSenderId: '742358725365',
    projectId: 'ftrainerlogbook',
    storageBucket: 'ftrainerlogbook.firebasestorage.app',
    iosBundleId: 'com.example.trainerlogbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCibaFjlPVFArgWh-dYeW33NZ7zOUHH1rk',
    appId: '1:742358725365:ios:7a45ba60ed1de60faf8bbc',
    messagingSenderId: '742358725365',
    projectId: 'ftrainerlogbook',
    storageBucket: 'ftrainerlogbook.firebasestorage.app',
    iosBundleId: 'com.example.trainerlogbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCibaFjlPVFArgWh-dYeW33NZ7zOUHH1rk',
    appId: '1:742358725365:web:7a45ba60ed1de60faf8bbc',
    messagingSenderId: '742358725365',
    projectId: 'ftrainerlogbook',
    authDomain: 'ftrainerlogbook.firebaseapp.com',
    storageBucket: 'ftrainerlogbook.firebasestorage.app',
  );
}
