name: Build iOS for TestFlight

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'App version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      build_number:
        description: 'Build number (e.g., 1)'
        required: true
        default: '1'

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v4
      with:
        flutter-version: 'stable'
        channel: 'stable'
        
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          ${{ github.workspace }}/.dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
          
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Setup iOS certificates
      uses: apple-actions/import-codesigning-certs@v2
      with:
        p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
        p12-password: ${{ secrets.IOS_P12_PASSWORD }}
        
    - name: Setup provisioning profile
      uses: apple-actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.example.trainerlogbook'
        profile-type: 'IOS_APP_STORE'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        
    - name: Build iOS app
      run: |
        # 设置版本号
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
          BUILD_NUMBER="${{ github.event.inputs.build_number }}"
        else
          # 从tag获取版本号
          VERSION=${GITHUB_REF#refs/tags/v}
          BUILD_NUMBER=$(date +%s)
        fi
        
        echo "Building version $VERSION+$BUILD_NUMBER"
        
        # 构建iOS应用
        flutter build ios --release --build-name=$VERSION --build-number=$BUILD_NUMBER
        
    - name: Create IPA
      run: |
        # 创建IPA文件
        cd build/ios/iphoneos
        xcrun altool --upload-app --type ios --file Runner.ipa --username ${{ secrets.APPSTORE_CONNECT_USERNAME }} --password ${{ secrets.APPSTORE_CONNECT_APP_SPECIFIC_PASSWORD }} --asc-provider ${{ secrets.APPSTORE_TEAM_ID }}
        
    - name: Upload to TestFlight
      run: |
        # 使用fastlane上传到TestFlight
        gem install fastlane
        fastlane pilot upload --ipa build/ios/iphoneos/Runner.ipa --username ${{ secrets.APPSTORE_CONNECT_USERNAME }} --app_identifier com.example.trainerlogbook
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          iOS build for TestFlight
          
          Version: ${{ github.ref_name }}
          Build: $(date +%s)
          
          Download the app from TestFlight for testing.
        draft: false
        prerelease: false
