name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'
        
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          ${{ github.workspace }}/.dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
          
    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: ${{ env.FLUTTER_ROOT }}
        key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-sdk-
          
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Build Flutter Web
      run: flutter build web --release
      
    - name: Copy vercel.json to build directory
      run: cp vercel.json build/web/vercel.json
        
    - name: Install Vercel CLI
      run: npm install -g vercel@latest
      
    - name: Deploy to Vercel
      run: vercel --cwd build/web --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        
    - name: Print build logs on failure
      if: failure()
      run: |
        echo "Build failed. Checking for error logs..."
        if [ -f "build/web/index.html" ]; then
          echo "Build output exists:"
          ls -la build/web/
        else
          echo "No build output found"
        fi
